### ISSUE TITLE
Licensing from Highcharts

### ISSUE THREAD

**Issue by Kyrremann** [dschenck/easychart#2]
We're looking into using Easychart at my job, but we're curious how your licensing works with Highcharts paid licensing. I tried to find something about this in your documentation, but there where no words about needing to buy the Highchart licensing when using Easychart.

**Comment by dschenck** [comment]
easychart is merely a wrapper around Highcharts. Depending on your use, you may need to get an appropriate license from Highcharts directly.

https://shop.highcharts.com/

You can think of easychart as a tool to generate a Highcharts configuration rather than a substitute thereof.

**Comment by Kyrremann** [comment]
Thanks for the quick response! That was what we thought too, it just wasn't clear from reading the documentation.

**Comment by dschenck** [comment]
Thanks for the heads up - will update docs accordingly
